---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: infinispan
  name: infinispan-monitoring
spec:
  endpoints:
    - interval: 30s
      scheme: http
      port: http
      path: /actuator/prometheus
  namespaceSelector:
    matchNames:
      - customers
  selector:
    matchLabels:
      app: customer-service-cache-springboot
