apiVersion: v1
kind: Secret
metadata:
  name: infinispan-basic-auth
  namespace: infinispan
stringData:
  identities.yaml: |- 
    credentials:
    - username: developer
      password: dIRs5cAAsHIeeRIL
    - username: operator
      password: uMBo9CmEdEduYk24
---
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan-minimal
  namespace: infinispan
spec:
  image: infinispan/server:11.0
  replicas: 3
  service:
    type: DataGrid
  security:
    endpointSecretName: infinispan-basic-auth
