kind: Secret
apiVersion: v1
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AUTH_TYPE: k8s
  K8S_ROLE: argocd
  TYPE: vault
  VAULT_ADDR: http://vault.vault.svc:8200
