{
 "title": "KEDA",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{consumergroup=\"lag-consumer-test\"}",
     "legendFormat": "Lag from Prometheus"
    },
    {
     "expr": "keda_metrics_adapter_scaler_metrics_value",
     "legendFormat": "Lag from KEDA"
    }
   ]
  },
  {
   "title": "Client Workload",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(irate(k6_kafka_writer_message_count_total[$__interval]))",
     "legendFormat": "scenario workload"
    }
   ]
  },
  {
   "title": "Consumer Replicas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kafka_consumergroup_members{consumergroup=\"lag-consumer-test\"}",
     "legendFormat": "ConsumerGroup members"
    },
    {
     "expr": "kube_deployment_status_replicas{deployment=\"kafka-deterministic-consumer\"}",
     "legendFormat": "Deployment Replicas"
    }
   ]
  }
 ]
}